# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: |
  (?x)(
    ^.+/generated/.*$
  )

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/crate-ci/typos
    rev: v1.28.3
    hooks:
      - id: typos
        exclude: |
          (?x)(
            \.spec$
          )
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
